[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
gas_reports = ['contracts\YieldStEthLever.sol:YieldStEthLever', 'contracts\YieldNotionalLever.sol:YieldNotionalLever']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
