[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
gas_reports = ['YieldStEthLever', 'YieldNotionalLever', 'YieldEulerLever']
rpc_endpoints = { MAINNET = "${MAINNET_RPC}", ARBITRUM = "${ARBITRUM_RPC}" ,TENDERLY = "${TENDERLY_RPC}"}
[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
