/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOracle } from "./IOracle";
export * as factories from "./factories";
export { IOracle__factory } from "./factories/IOracle__factory";
