/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IJoin, IJoinInterface } from "../IJoin";

const _abi = [
  {
    inputs: [],
    name: "asset",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "wad",
        type: "uint128",
      },
    ],
    name: "exit",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "wad",
        type: "uint128",
      },
    ],
    name: "join",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IJoin__factory {
  static readonly abi = _abi;
  static createInterface(): IJoinInterface {
    return new utils.Interface(_abi) as IJoinInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IJoin {
    return new Contract(address, _abi, signerOrProvider) as IJoin;
  }
}
