/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ITokenInterface extends utils.Interface {
  functions: {
    "flashBorrow(uint256,address,address,string,bytes)": FunctionFragment;
    "loanTokenAddress()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "flashBorrow" | "loanTokenAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "flashBorrow",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "loanTokenAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "flashBorrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "loanTokenAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IToken extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITokenInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    flashBorrow(
      borrowAmount: PromiseOrValue<BigNumberish>,
      borrower: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      signature: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    loanTokenAddress(overrides?: CallOverrides): Promise<[string]>;
  };

  flashBorrow(
    borrowAmount: PromiseOrValue<BigNumberish>,
    borrower: PromiseOrValue<string>,
    target: PromiseOrValue<string>,
    signature: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  loanTokenAddress(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    flashBorrow(
      borrowAmount: PromiseOrValue<BigNumberish>,
      borrower: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      signature: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    loanTokenAddress(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    flashBorrow(
      borrowAmount: PromiseOrValue<BigNumberish>,
      borrower: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      signature: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    loanTokenAddress(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    flashBorrow(
      borrowAmount: PromiseOrValue<BigNumberish>,
      borrower: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      signature: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    loanTokenAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
