name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  foundry-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build contracts
        run: forge build

      - name: Check gas consumption
        run: forge snapshot --check --fork-url ${{ secrets.ALCHEMY_MAINNET_RPC }}

      - name: Run tests
        run: forge test -vvv --fork-url ${{ secrets.ALCHEMY_MAINNET_RPC }}